#!/bin/bash

BACKUP_DIR="/home/minecraft/backup"
SERVER_DIR="/home/minecraft/server"
MAX_FILE_COUNT=28

usage() {
  echo "Usage: $(basename "$0") [-r]"
  echo
  echo "Options:"
  echo "  -r  Remove old backups (keep $MAX_FILE_COUNT most recent)"
  exit 1
}

save_world() {
  send_to_server "say Backing up server..."
  sleep 0.1 # Ensure the message is sent before the save command runs

  local log_file="$SERVER_DIR/logs/latest.log"
  local start_line=$(wc -l < "$log_file")
  local timeout=30 # In seconds
  local elapsed=0

  send_to_server "save-off" # Disable autosave
  send_to_server "save-all flush" # Save world manually

  while ((elapsed <= $timeout)); do
    printf "\rSaving world (%d/%ds)... " $elapsed $timeout

    # Check log file for "Saved the game" message
    local new_lines=$(tail -n +"$start_line" "$log_file")
    if echo "$new_lines" | grep -q "Saved the game"; then
      echo "done!"
      return
    fi

    sleep 1 && ((elapsed++))
  done

  send_to_server "save-on"
  send_to_server "say Failed to save world"

  echo "Error: Failed to save world"
  exit 1
}

remove_old_backups() {
  # Remove oldest backups if exceeding limit
  if [[ $(ls "$BACKUP_DIR" | wc -l) -gt $MAX_FILE_COUNT ]]; then
    printf "Removing oldest backup(s)... "
    rm $(ls -rtd $BACKUP_DIR/* | head -n -$MAX_FILE_COUNT)
    echo "done!"
  fi
}

send_to_server() {
  screen -S minecraft-server -X stuff "$1^M"
}

if [[ $# -gt 0 ]]; then
  case "$1" in
    -r) remove_old_backups=true ;;
    *) echo "Invalid option: $1"; usage ;;
  esac
fi

if screen -ls | grep -qF "minecraft-server"; then
  save_world
fi

# Create a new backup
printf "Creating backup... "
tar -czf "$BACKUP_DIR/$(date +%F-%H-%M-%S).tgz" -C "$SERVER_DIR" "world" "world_nether" "world_the_end"
echo "done!"

# Re-enable autosave
if screen -ls | grep -qF "minecraft-server"; then
  send_to_server "save-on"
  send_to_server "say Backup complete!"
fi

if [[ "$remove_old_backups" == true ]]; then
  remove_old_backups
fi
