#!/bin/bash

SERVER_DIR="/home/minecraft/server"
BACKUP_DIR="/home/minecraft/backup"

usage() {
  echo "Usage: $(basename "$0") [-f] [-l] archive"
  echo
  echo "Options:"
  echo "  -f       Force restart server without confirmation"
  echo "  -l       Restore latest archive in $BACKUP_DIR"
  echo "  archive  Path to backup archive"
  exit 1
}

restore() {
  printf "Restoring $1... "

  rm -rf "$SERVER_DIR/world"

  if tar -xzf "$1" -C "$SERVER_DIR"; then
    echo "done!"
  else
    echo "Error: Failed to extract the archive"
    exit 1
  fi
}

confirm() {
  echo "Warning: Restoring \"$1\" will erase all current server data"
  read -rp "Do you wish to continue? [y/N] " confirm
  [[ "$confirm" =~ ^[Yy]$ ]]
}

# Parse flags
while getopts ":fl" opt; do
  case "$opt" in
    f) force=true ;;
    l) latest=true ;;
    ?) echo "Invalid option: -$OPTARG" && usage ;;
  esac
done
shift $((OPTIND - 1))

if [[ $latest == true ]]; then
  if [[ $(ls "$BACKUP_DIR" | wc -l) -eq 0 ]]; then
    echo "Error: No backups present in $BACKUP_DIR"
    exit 1
  fi
  # Restore latest backup
  filename=$(ls -td $BACKUP_DIR/* | head -n 1)
else
  if [[ $# -eq 0 ]]; then
    echo "Error: No archive file provided" && usage
  fi
  if [[ ! -f "$1" ]]; then
    echo "Error: Archive file \"$1\" does not exist" && usage
  fi
  filename=$1
fi

if screen -ls | grep -qF "minecraft-server"; then
  if [[ $force == true ]]; then
    /home/minecraft/scripts/mc-stop
    restore "$filename"
    /home/minecraft/scripts/mc-start
  else
    echo "Error: Server is running"
    exit 1
  fi
else
  if [[ $force == true ]] || confirm "$filename"; then
    restore "$filename"
  else
    echo "Restore cancelled"
  fi
fi
