#!/bin/bash

SERVER_DIR="/home/minecraft/server"
MEMORY_MIN="8G"
MEMORY_MAX="8G"

# Aikar's recommended JVM flags
JVM_FLAGS=(
  -XX:+AlwaysPreTouch
  -XX:+DisableExplicitGC
  -XX:+ParallelRefProcEnabled
  -XX:+PerfDisableSharedMem
  -XX:+UnlockExperimentalVMOptions
  -XX:+UseG1GC
  -XX:G1HeapRegionSize=8M
  -XX:G1HeapWastePercent=5
  -XX:G1MaxNewSizePercent=40
  -XX:G1MixedGCCountTarget=4
  -XX:G1MixedGCLiveThresholdPercent=90
  -XX:G1NewSizePercent=30
  -XX:G1RSetUpdatingPauseTimePercent=5
  -XX:G1ReservePercent=20
  -XX:InitiatingHeapOccupancyPercent=15
  -XX:MaxGCPauseMillis=200
  -XX:MaxTenuringThreshold=1
  -XX:SurvivorRatio=32
  -Dusing.aikars.flags=https://mcflags.emc.gs
  -Daikars.new.flags=true
)

# Check if server is already running
if ! screen -ls | grep -qF "minecraft-server"; then
  echo "Starting server..."
  screen -dmS minecraft-server bash -c "cd '$SERVER_DIR' && java -Xms$MEMORY_MIN -Xmx$MEMORY_MAX ${JVM_FLAGS[*]} -jar paper.jar --nogui"
else
  echo "Server is already running"
fi

echo "Run \"screen -dr minecraft-server\" to attach"
