#!/bin/bash

TIMEOUT=30 # In seconds

if ! screen -ls | grep -qF "minecraft-server"; then
  echo "Server is not running"
  exit 0
fi

# Stop the server
screen -S minecraft-server -X stuff "stop^M"

# Wait for the server to exit cleanly
while screen -ls | grep -qF "minecraft-server"; do
  printf "\rStopping server (%d/%ds)... " $SECONDS $TIMEOUT
  if ((SECONDS >= TIMEOUT)); then
    printf "\nError: Server did not stop within $TIMEOUT seconds\n"
    exit 1
  fi
  sleep 1
done
echo "done!"
