#!/bin/bash

SERVER_DIR="/home/minecraft/server"
MEMORY_MIN="10G"
MEMORY_MAX="10G"

# Check if server is already running
if ! screen -ls | grep -qF "minecraft-server"; then
  echo "Starting server..."
  screen -dmS minecraft-server bash -c "cd '$SERVER_DIR' && java -Xms$MEMORY_MIN -Xmx$MEMORY_MAX -jar paper.jar --nogui"
else
  echo "Server is already running"
fi

echo "Run \"screen -dr minecraft-server\" to attach"
